const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirts',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: '4.5',
      numReviews: 10,
      description: 'High Quality Product',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirts',
      category: 'Shirts',
      image: '/images/p2.webp',
      price: 100,
      countInStock: 20,
      brand: 'Nike',
      rating: '4.5',
      numReviews: 10,
      description: 'High Quality Product',
    },
    {
      _id: '3',
      name: 'Lacoste Free Shirts',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Nike',
      rating: '4.5',
      numReviews: 10,
      description: 'High Quality Product',
    },
    {
      _id: '4',
      name: 'Nike Slim Pants',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 180,
      countInStock: 15,
      brand: 'Nike',
      rating: '4.5',
      numReviews: 10,
      description: 'High Quality Product',
    },
    {
      _id: '5',
      name: 'Nike Slim Shirts',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 78,
      countInStock: 5,
      brand: 'Puma',
      rating: '4.5',
      numReviews: 10,
      description: 'High Quality Product',
    },
    {
      _id: '6',
      name: 'Nike Slim Shirts',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Nike',
      rating: '4.5',
      numReviews: 10,
      description: 'High Quality Product',
    },
  ],
};

export default data;